### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by ajsb85** [comment]
Hi @ZuBB 

What's about this pull-request?

Salut.

**Comment by ZuBB** [comment]
yes, sure

**Comment by Kristinita** [comment]
@ZuBB , please, push this change to npm, that grunt-git-them-all users don't get a warning:

```node
npm WARN grunt-git-them-all@0.0.13 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
```

Thanks.

**Comment by Kristinita** [comment]
@ZuBB , ping.

Thanks.

**Comment by ZuBB** [comment]
Hi @Kristinita!

sorry for a delay (just come back from trip 😃 ). best I cap promise is that I will have some time for this on next week.

Meanwhile I would recommend to consider this https://github.com/ZuBB/grunt-git-them-all/commit/32eae386bf6bfd2f24f900329c148d851b54c811#diff-04c6e90faac2675aa89e2176d2eec7d8 

there I recommend better alternative.

**Comment by Kristinita** [comment]
@ZuBB , 

+ grunt-simply-git do not update 3 years (and it have [**outdated dependencies**](https://github.com/tandrewnichols/grunt-simple-git/pull/3))
+ grunt-git-them-all — 1 year.

> sorry for a delay (just come back from trip 😃 ). best I cap promise is that I will have some time for this on next week.

We are waiting.

Thanks.

**Comment by Kristinita** [comment]
@ZuBB , relevance at May 2018.

Thanks.

**Pull request merged**
